# Generated by Django 3.1 on 2020-10-17 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('sex', models.CharField(choices=[('M', 'MAN'), ('W', 'WOMAN')], max_length=1)),
                ('birthday', models.DateField()),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('TECH', 'TECH'), ('FUN CONTENT', 'FUN CONTENT'), ('BEAUTY', 'BEAUTY'), ('FASHION', 'FACHION')], max_length=100)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.blogger')),
            ],
        ),
        migrations.CreateModel(
            name='BlogLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'ENGLISH'), ('RU', 'RUSSIAN'), ('PL', 'POLISH')], max_length=2)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.blogger')),
            ],
        ),
    ]
