# Generated by Django 3.1 on 2020-10-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_auto_20201018_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspecialization',
            name='specialization',
            field=models.CharField(choices=[('TECH', 'Tech'), ('FUN CONTENT', 'Fun content'), ('BEAUTY', 'Beauty'), ('FASHION', 'Fashion')], max_length=100),
        ),
    ]
