# Generated by Django 3.1 on 2020-10-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='state',
        ),
    ]
