# Generated by Django 3.1 on 2020-10-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_location_blogger'),
        ('offer', '0002_remove_offer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggermodel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.location'),
        ),
        migrations.CreateModel(
            name='ReceivingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.BooleanField(default=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.location')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='receiving_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.receivingmodel'),
        ),
    ]
