# Generated by Django 3.1 on 2020-10-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20201030_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivingmodel',
            name='location',
        ),
        migrations.AddField(
            model_name='receivingmodel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
