# Generated by Django 3.1 on 2020-10-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_auto_20201030_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggermodel',
            name='sex',
            field=models.CharField(choices=[('M', 'MAN'), ('W', 'WOMAN'), ('ANY', 'ANY')], max_length=3),
        ),
    ]
