# Generated by Django 3.1 on 2020-10-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_auto_20201030_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggermodel',
            name='subscribers_number_group',
            field=models.CharField(default=3, max_length=50),
        ),
        migrations.AlterField(
            model_name='bloggermodel',
            name='age_group',
            field=models.CharField(choices=[('KIDS', 'Kids'), ('TEENAGERS', 'Teenagers'), ('ADULTS', 'Adults'), ('OLD', 'Old')], max_length=50),
        ),
    ]
