# Generated by Django 3.1 on 2020-10-31 12:31

from django.db import migrations, models
import offer.utils


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_auto_20201031_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=offer.utils.upload_image_path_offer),
        ),
    ]
