# Generated by Django 3.1 on 2020-10-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_offer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribersNumberGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('blogger_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.bloggermodel')),
            ],
        ),
    ]
