# Generated by Django 3.1 on 2020-10-31 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_subscribersnumbergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggermodel',
            name='subscribers_number_group',
        ),
    ]
