# Generated by Django 3.1 on 2020-12-14 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_auto_20201113_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggermodellanguage',
            name='blogger_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='offer.bloggermodel'),
        ),
        migrations.AlterField(
            model_name='bloggermodelspecialization',
            name='blogger_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='offer.bloggermodel'),
        ),
        migrations.AlterField(
            model_name='subscribersnumbergroup',
            name='blogger_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_groups', to='offer.bloggermodel'),
        ),
    ]
