# Generated by Django 3.1 on 2021-01-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_offer_offer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggermodel',
            name='age_group',
            field=models.CharField(choices=[('13–17', '13–17 years'), ('18–24', '18–24 years'), ('25–34', '25–34 years'), ('35–44', '35–44 years'), ('45–54', '45–54 years'), ('55–64', '55–64 years'), ('65+', '65+ years')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bloggermodel',
            name='sex',
            field=models.CharField(choices=[('M', 'MAN'), ('W', 'WOMAN'), ('ANY', 'ANY')], max_length=3),
        ),
    ]
