# Generated by Django 3.1 on 2021-01-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0017_auto_20210107_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggermodel',
            name='age_group',
        ),
        migrations.AddField(
            model_name='bloggermodel',
            name='max_subscribers',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='bloggermodel',
            name='min_subscribers',
            field=models.IntegerField(default=500000),
        ),
        migrations.CreateModel(
            name='BloggerModelAgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('13–17', '13–17 years'), ('18–24', '18–24 years'), ('25–34', '25–34 years'), ('35–44', '35–44 years'), ('45–54', '45–54 years'), ('55–64', '55–64 years'), ('65+', '65+ years')], max_length=50)),
                ('blogger_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_groups', to='offer.bloggermodel')),
            ],
        ),
    ]
