# Generated by Django 3.1 on 2021-01-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0018_auto_20210111_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribersNumberGroup',
        ),
    ]
