# Generated by Django 3.1 on 2021-01-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0019_delete_subscribersnumbergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='blogger_model',
        ),
        migrations.AddField(
            model_name='bloggermodel',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.offer'),
        ),
    ]
