# Generated by Django 3.1 on 2020-12-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailactivation',
            name='expires',
        ),
    ]
