# Generated by Django 3.1 on 2020-12-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_youtube_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='refresh_token',
            field=models.CharField(max_length=255),
        ),
    ]
