# Generated by Django 3.1 on 2020-12-28 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0010_remove_blogger_youtube'),
        ('youtube', '0003_auto_20201228_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='blogger',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='blogger.blogger'),
        ),
    ]
