# Generated by Django 3.1 on 2020-12-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_auto_20201228_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubemonthstatistics',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='youtubemonthstatistics',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='youtubemonthstatistics',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='youtubemonthstatistics',
            name='subscribers_gained',
        ),
        migrations.RemoveField(
            model_name='youtubemonthstatistics',
            name='views',
        ),
        migrations.AddField(
            model_name='youtubemonthstatistics',
            name='month_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubemonthstatistics',
            name='month_subscribers_gained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubemonthstatistics',
            name='total_dislikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubemonthstatistics',
            name='total_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubemonthstatistics',
            name='total_video_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubemonthstatistics',
            name='total_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubemonthstatistics',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
