# Generated by Django 3.1 on 2020-12-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_auto_20201230_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubemonthstatistics',
            old_name='total_dislikes',
            new_name='subscribers',
        ),
        migrations.RemoveField(
            model_name='youtubemonthstatistics',
            name='total_likes',
        ),
        migrations.AddField(
            model_name='youtube',
            name='channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
