# Generated by Django 3.1 on 2020-12-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_auto_20201230_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeManager',
        ),
    ]
