# Generated by Django 3.1 on 2021-01-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0010_auto_20210104_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='updated_token',
            field=models.DateTimeField(),
        ),
    ]
