# Generated by Django 3.1 on 2021-01-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_auto_20210105_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeAudienceManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('13–17', '13–17 years'), ('18–24', '18–24 years'), ('25–34', '25–34 years'), ('35–44', '35–44 years'), ('45–54', '45–54 years'), ('55–64', '55–64 years'), ('65+', '65+ years')], default='18-24', max_length=50)),
                ('sex', models.CharField(choices=[('M', 'MAN'), ('W', 'WOMAN')], default='M', max_length=1)),
                ('youtube', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='youtube.youtube')),
            ],
        ),
    ]
