# Generated by Django 3.1 on 2021-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0012_youtubeaudience_youtubeaudiencemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeaudience',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
