# Generated by Django 3.1 on 2021-01-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0013_youtubeaudience_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeAudienceManager',
        ),
    ]
