# Generated by Django 3.1 on 2021-01-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0014_delete_youtubeaudiencemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeaudience',
            name='age_group',
            field=models.CharField(default='18-24', max_length=50),
        ),
    ]
