# Generated by Django 3.1 on 2021-01-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0015_auto_20210105_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
