# Generated by Django 3.1 on 2020-12-14 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_auto_20201214_2014'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='offer.offer'),
        ),
        migrations.AlterField(
            model_name='applicationrate',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_rate', to='application.application'),
        ),
    ]
