# Generated by Django 3.1 on 2020-10-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_blogger_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglanguage',
            name='language',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='blogspecialization',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
