# Generated by Django 3.1 on 2020-10-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_auto_20201023_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='location',
        ),
    ]
