# Generated by Django 3.1 on 2020-10-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_location_blogger'),
        ('blogger', '0006_remove_blogger_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.location'),
        ),
    ]
