# Generated by Django 3.1 on 2020-12-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0009_auto_20201114_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='youtube',
        ),
    ]
