# Generated by Django 3.1 on 2021-01-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0010_remove_blogger_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglanguage',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blogspecialization',
            name='specialization',
            field=models.CharField(choices=[('BEAUTY', 'Beauty'), ('TRAVEL', 'Travelling'), ('KIDS', 'Kids'), ('SPORT', 'Sport'), ('HUMOR', 'Humor'), ('SOCIETY', 'Society'), ('BUSINESS/FINANCES', 'Business/Finances'), ('DESIGN', 'Design'), ('VIDEO GAMES', 'Video games'), ('ANIMALS', 'Animals'), ('TECH', 'Technologies/Gadgets'), ('IT', 'IT'), ('CREATIVITY', 'Creativity'), ('FOOD/DRINKS', 'Food/Drinks'), ('LIFESTYLE', 'Lifestyle'), ('MUSIC/MOVIES', 'Music/Movies'), ('EDUCATION', 'Education'), ('HEALTH', 'Health'), ('WEB-SITES/APPLICATIONS', 'Web-sites/Applications'), ('AUTO/MOTO', 'Auto/Moto'), ('BOOKS', 'Books'), ('HOUSE/RENOVATION', 'House/Renovation')], max_length=100),
        ),
    ]
