# Generated by Django 3.1 on 2020-10-18 15:03

import business.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=business.utils.upload_image_path_business),
        ),
    ]
