# Generated by Django 3.1 on 2020-10-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('BLR', 'BELARUS'), ('RUS', 'RUSSIA'), ('USA', 'UNITES STATES OF AMERICA')], max_length=3)),
                ('city', models.CharField(choices=[('MINSK', 'MINSK'), ('MOSKOW', 'MOSKOW'), ('WASHINGTON', 'WASHINGTON')], max_length=120)),
            ],
        ),
    ]
