# Generated by Django 3.1 on 2020-10-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0006_remove_blogger_location'),
        ('account', '0003_auto_20201023_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='blogger',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogger.blogger'),
            preserve_default=False,
        ),
    ]
