# Generated by Django 3.1 on 2020-11-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_location_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
