# Generated by Django 3.1 on 2020-11-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_id',
        ),
    ]
